version: "3.7"

services:
  oi-exporter:
    image: golang:1.21.3
    working_dir: /usr/opt/oi-exporter
    command: bash -c 'go install && /go/bin/oi-exporter'
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/opt/oi-exporter

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./deploy/prometheus:/etc/prometheus:ro
      - prometheus:/prometheus
    command: |
      --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:7.5.17
    volumes:
      - "./deploy/grafana/dashboards:/var/lib/grafana/dashboards:ro"
      - "./deploy/grafana/datasources:/etc/grafana/provisioning/datasources"
      - "./deploy/grafana/provision_dashboard.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus:
