{
 "title": "Open Interest",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "expiry_date",
    "label": "Expiry Date",
    "query": {
     "query": "label_values(oi_exporter_open_interest, expiry_date)"
    }
   },
   {
    "name": "strike_price",
    "label": "Strike Price",
    "query": {
     "query": "label_values(oi_exporter_open_interest{expiry_date=\"$expiry_date\"}, strike_price)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Option Price vs OI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CE Open Interest vs Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oi_exporter_open_interest{expiry_date=\"$expiry_date\",strike_price=~\"$strike_price\",option_type=\"CE\"}",
     "legendFormat": "{{symbol}} {{strike_price}} CE: OI"
    },
    {
     "expr": "oi_exporter_last_price{expiry_date=\"$expiry_date\",strike_price=~\"$strike_price\",option_type=\"CE\"}",
     "legendFormat": "{{symbol}} {{strike_price}} CE: Price"
    }
   ]
  },
  {
   "title": "PE Open Interest vs Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oi_exporter_open_interest{expiry_date=\"$expiry_date\",strike_price=~\"$strike_price\",option_type=\"PE\"}",
     "legendFormat": "{{symbol}} {{strike_price}} PE: OI"
    },
    {
     "expr": "oi_exporter_last_price{expiry_date=\"$expiry_date\",strike_price=~\"$strike_price\",option_type=\"PE\"}",
     "legendFormat": "{{symbol}} {{strike_price}} PE: Price"
    }
   ]
  },
  { "title": "Call vs Put OI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CE vs PE OI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oi_exporter_open_interest{expiry_date=\"$expiry_date\",strike_price=~\"$strike_price\",option_type=\"CE\"}",
     "legendFormat": "{{symbol}} {{strike_price}} CE"
    },
    {
     "expr": "oi_exporter_open_interest{expiry_date=\"$expiry_date\",strike_price=~\"$strike_price\",option_type=\"PE\"}",
     "legendFormat": "{{symbol}}  {{strike_price}} PE"
    }
   ]
  },
  {
   "title": "Spot Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "currencyINR" }
   ],
   "targets": [
    { "expr": "oi_exporter_underlying_value{}", "legendFormat": "{{symbol}}" }
   ]
  }
 ]
}